# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual modifys made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from course_inquiry_ui import Ui_Window_course_inquiry
from score_inquiry_ui import Ui_Window_score_inquiry
from stuinfo_inquiry_ui import Ui_Window_stuinfo_inquiry
from score_add_ui import Ui_Window_score_add
from score_delete_ui import Ui_Window_score_delete
from score_modify_ui import Ui_Window_score_modify
from stuinfo_add_ui import Ui_Window_stuinfo_add
from stuinfo_delete_ui import Ui_Window_stuinfo_delete
from stuinfo_modify_ui import Ui_Window_stuinfo_modify
from help_ui import Ui_Window_help


class Ui_Window_admin(object):
    def setupUi(self, Window_admin):
        Window_admin.setObjectName("Window_admin")
        Window_admin.resize(1280, 720)
        Window_admin.setMinimumSize(QtCore.QSize(1280, 720))
        Window_admin.setMaximumSize(QtCore.QSize(1280, 720))
        self.icon = QtGui.QIcon()
        self.icon.addPixmap(QtGui.QPixmap(":/icon/res/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.centralwidget = QtWidgets.QWidget(Window_admin)
        self.centralwidget.setObjectName("centralwidget")
        Window_admin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Window_admin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        self.action_course = QtWidgets.QAction(Window_admin)
        self.action_course.setObjectName("action_course")
        self.action_score = QtWidgets.QAction(Window_admin)
        self.action_score.setObjectName("action_score")
        self.action_stuinfo = QtWidgets.QAction(Window_admin)
        self.action_stuinfo.setObjectName("action_stuinfo")
        self.menu_stuinfo = QtWidgets.QMenu(self.menubar)
        self.menu_stuinfo.setObjectName("menu_stuinfo")
        self.menu_score = QtWidgets.QMenu(self.menubar)
        self.menu_score.setObjectName("menu_score")
        self.action_help = QtWidgets.QAction(Window_admin)
        self.action_help.setObjectName("action_help")
        self.action_exit = QtWidgets.QAction(Window_admin)
        self.action_exit.setObjectName("action_exit")
        Window_admin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Window_admin)
        self.statusbar.setObjectName("statusbar")
        Window_admin.setStatusBar(self.statusbar)
        self.action_score_add = QtWidgets.QAction(Window_admin)
        self.action_score_add.setObjectName("action_score_add")
        self.action_score_modify = QtWidgets.QAction(Window_admin)
        self.action_score_modify.setObjectName("action_score_modify")
        self.action_score_delete = QtWidgets.QAction(Window_admin)
        self.action_score_delete.setObjectName("action_score_delete")
        self.action_stuinfo_add = QtWidgets.QAction(Window_admin)
        self.action_stuinfo_add.setObjectName("action_stuinfo_add")
        self.action_stuinfo_modify = QtWidgets.QAction(Window_admin)
        self.action_stuinfo_modify.setObjectName("action_stuinfo_modify")
        self.action_stuinfo_delete = QtWidgets.QAction(Window_admin)
        self.action_stuinfo_delete.setObjectName("action_stuinfo_delete")
        self.menu_stuinfo.addAction(self.action_stuinfo_add)
        self.menu_stuinfo.addAction(self.action_stuinfo_modify)
        self.menu_stuinfo.addAction(self.action_stuinfo_delete)
        self.menu_score.addAction(self.action_score_add)
        self.menu_score.addAction(self.action_score_modify)
        self.menu_score.addAction(self.action_score_delete)

        self.menubar.addAction(self.action_course)
        self.menubar.addAction(self.action_score)
        self.menubar.addAction(self.action_stuinfo)
        self.menubar.addAction(self.menu_score.menuAction())
        self.menubar.addAction(self.menu_stuinfo.menuAction())
        self.menubar.addAction(self.action_help)
        self.menubar.addAction(self.action_exit)

        self.retranslateUi(Window_admin)
        QtCore.QMetaObject.connectSlotsByName(Window_admin)
        Window_admin.setWindowIcon(self.icon)
        # 退出登录
        self.action_exit.triggered.connect(Window_admin.close)
        # 跳转开课情况查询
        self.action_course.triggered.connect(lambda: self.go_course_inquiry(Window_admin))
        self.action_score.triggered.connect(lambda: self.go_score_inquiry(Window_admin))
        self.action_stuinfo.triggered.connect(lambda: self.go_stuinfo_inquiry(Window_admin))
        self.action_score_add.triggered.connect(lambda: self.go_score_add(Window_admin))
        self.action_score_delete.triggered.connect(lambda: self.go_score_delete(Window_admin))
        self.action_score_modify.triggered.connect(lambda: self.go_score_modify(Window_admin))
        self.action_help.triggered.connect(lambda: self.go_help(Window_admin))
        self.action_stuinfo_add.triggered.connect(lambda: self.go_stuinfo_add(Window_admin))
        self.action_stuinfo_delete.triggered.connect(lambda: self.go_stuinfo_delete(Window_admin))
        self.action_stuinfo_modify.triggered.connect(lambda: self.go_stuinfo_modify(Window_admin))

    def retranslateUi(self, Window_admin):
        _translate = QtCore.QCoreApplication.translate
        Window_admin.setWindowTitle(_translate("Window_admin", "管理员系统"))
        self.action_course.setText(_translate("Window_admin", "开课情况查询"))
        self.action_score.setText(_translate("Window_admin", "学生成绩查询"))
        self.action_stuinfo.setText(_translate("Window_admin", "学生信息查询"))
        self.menu_stuinfo.setTitle(_translate("Window_admin", "学生记录维护"))
        self.menu_score.setTitle(_translate("Window_admin", "学生成绩维护"))
        self.action_help.setText(_translate("Window_admin", "帮助"))
        self.action_exit.setText(_translate("Window_admin", "退出登录"))
        self.action_score_add.setText(_translate("Window_admin", "添加成绩记录"))
        self.action_score_modify.setText(_translate("Window_admin", "修改成绩记录"))
        self.action_score_delete.setText(_translate("Window_admin", "删除成绩记录"))
        self.action_stuinfo_add.setText(_translate("Window_admin", "添加学生记录"))
        self.action_stuinfo_modify.setText(_translate("Window_admin", "修改学生记录"))
        self.action_stuinfo_delete.setText(_translate("Window_admin", "删除学生记录"))

    def go_course_inquiry(self, Window_admin):
        course_inquiry = Ui_Window_course_inquiry()
        Maintain = QtWidgets.QMainWindow()
        course_inquiry.setupUi(Maintain)
        Window_admin.setCentralWidget(Maintain)

    def go_score_inquiry(self, Window_admin):
        score_inquiry = Ui_Window_score_inquiry()
        Maintain = QtWidgets.QMainWindow()
        score_inquiry.setupUi(Maintain)
        Window_admin.setCentralWidget(Maintain)

    def go_stuinfo_inquiry(self, Window_admin):
        stuinfo_inquiry = Ui_Window_stuinfo_inquiry()
        Maintain = QtWidgets.QMainWindow()
        stuinfo_inquiry.setupUi(Maintain)
        Window_admin.setCentralWidget(Maintain)

    def go_score_add(self, Window_admin):
        score_add = Ui_Window_score_add()
        Maintain = QtWidgets.QMainWindow()
        score_add.setupUi(Maintain)
        Window_admin.setCentralWidget(Maintain)

    def go_score_delete(self, Window_admin):
        score_delete = Ui_Window_score_delete()
        Maintain = QtWidgets.QMainWindow()
        score_delete.setupUi(Maintain)
        Window_admin.setCentralWidget(Maintain)

    def go_score_modify(self, Window_admin):
        score_modify = Ui_Window_score_modify()
        Maintain = QtWidgets.QMainWindow()
        score_modify.setupUi(Maintain)
        Window_admin.setCentralWidget(Maintain)

    def go_help(self, Window_admin):
        help = Ui_Window_help()
        Maintain = QtWidgets.QMainWindow()
        help.setupUi(Maintain)
        Window_admin.setCentralWidget(Maintain)

    def go_stuinfo_add(self, Window_admin):
        stuinfo_add = Ui_Window_stuinfo_add()
        Maintain = QtWidgets.QMainWindow()
        stuinfo_add.setupUi(Maintain)
        Window_admin.setCentralWidget(Maintain)

    def go_stuinfo_delete(self, Window_admin):
        stuinfo_delete = Ui_Window_stuinfo_delete()
        Maintain = QtWidgets.QMainWindow()
        stuinfo_delete.setupUi(Maintain)
        Window_admin.setCentralWidget(Maintain)

    def go_stuinfo_modify(self, Window_admin):
        stuinfo_modify = Ui_Window_stuinfo_modify()
        Maintain = QtWidgets.QMainWindow()
        stuinfo_modify.setupUi(Maintain)
        Window_admin.setCentralWidget(Maintain)