# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generaluser_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual modifys made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from course_inquiry_ui import Ui_Window_course_inquiry
from score_inquiry_ui import Ui_Window_score_inquiry
from stuinfo_inquiry_ui import Ui_Window_stuinfo_inquiry
from score_add_ui import Ui_Window_score_add
from score_delete_ui import Ui_Window_score_delete
from score_modify_ui import Ui_Window_score_modify
from stuinfo_add_ui import Ui_Window_stuinfo_add
from stuinfo_delete_ui import Ui_Window_stuinfo_delete
from stuinfo_modify_ui import Ui_Window_stuinfo_modify
from help_ui import Ui_Window_help

class Ui_Window_generaluser(object):
    def setupUi(self, Window_generaluser):
        Window_generaluser.setObjectName("Window_generaluser")
        Window_generaluser.resize(1280, 720)
        Window_generaluser.setMinimumSize(QtCore.QSize(1280, 720))
        Window_generaluser.setMaximumSize(QtCore.QSize(1280, 720))
        self.icon = QtGui.QIcon()
        self.icon.addPixmap(QtGui.QPixmap(":/icon/res/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.centralwidget = QtWidgets.QWidget(Window_generaluser)
        self.centralwidget.setObjectName("centralwidget")
        Window_generaluser.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Window_generaluser)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        self.action_course = QtWidgets.QAction(Window_generaluser)
        self.action_course.setObjectName("action_course")
        self.action_score = QtWidgets.QAction(Window_generaluser)
        self.action_score.setObjectName("action_score")
        self.action_help = QtWidgets.QAction(Window_generaluser)
        self.action_help.setObjectName("action_help")
        self.action_exit = QtWidgets.QAction(Window_generaluser)
        self.action_exit.setObjectName("action_exit")
        Window_generaluser.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Window_generaluser)
        self.statusbar.setObjectName("statusbar")
        Window_generaluser.setStatusBar(self.statusbar)
        self.menubar.addAction(self.action_course)
        self.menubar.addAction(self.action_score)
        self.menubar.addAction(self.action_help)
        self.menubar.addAction(self.action_exit)

        self.retranslateUi(Window_generaluser)
        QtCore.QMetaObject.connectSlotsByName(Window_generaluser)
        Window_generaluser.setWindowIcon(self.icon)

        self.action_exit.triggered.connect(Window_generaluser.close)

        self.action_course.triggered.connect(lambda: self.go_course_inquiry(Window_generaluser))
        self.action_score.triggered.connect(lambda: self.go_score_inquiry(Window_generaluser))
        self.action_help.triggered.connect(lambda: self.go_help(Window_generaluser))

    def retranslateUi(self, Window_generaluser):
        _translate = QtCore.QCoreApplication.translate
        Window_generaluser.setWindowTitle(_translate("Window_generaluser", "普通用户系统"))
        self.action_course.setText(_translate("Window_generaluser", "开课情况查询"))
        self.action_score.setText(_translate("Window_generaluser", "学生成绩查询"))
        self.action_help.setText(_translate("Window_generaluser", "帮助"))
        self.action_exit.setText(_translate("Window_generaluser", "退出登录"))

    def go_course_inquiry(self,Window_generaluser):
        course_inquiry = Ui_Window_course_inquiry()
        Maintain = QtWidgets.QMainWindow()
        course_inquiry.setupUi(Maintain)
        Window_generaluser.setCentralWidget(Maintain)

    def go_score_inquiry(self, Window_generaluser):
        score_inquiry = Ui_Window_score_inquiry()
        Maintain = QtWidgets.QMainWindow()
        score_inquiry.setupUi(Maintain)
        Window_generaluser.setCentralWidget(Maintain)

    def go_help(self, Window_generaluser):
        help = Ui_Window_help()
        Maintain = QtWidgets.QMainWindow()
        help.setupUi(Maintain)
        Window_generaluser.setCentralWidget(Maintain)
