# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window_help(object):
    def setupUi(self, Window_help):
        Window_help.setObjectName("Window_help")
        Window_help.resize(1280, 720)
        self.label_title1 = QtWidgets.QLabel(Window_help)
        self.label_title1.setGeometry(QtCore.QRect(350, 20, 580, 60))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.label_title1.setFont(font)
        self.label_title1.setObjectName("label_title1")
        self.label_version = QtWidgets.QLabel(Window_help)
        self.label_version.setGeometry(QtCore.QRect(930, 40, 190, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_version.setFont(font)
        self.label_version.setObjectName("label_version")
        self.label_title2 = QtWidgets.QLabel(Window_help)
        self.label_title2.setGeometry(QtCore.QRect(580, 160, 120, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.label_title2.setFont(font)
        self.label_title2.setObjectName("label_title2")
        self.label_producer = QtWidgets.QLabel(Window_help)
        self.label_producer.setGeometry(QtCore.QRect(485, 220, 310, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_producer.setFont(font)
        self.label_producer.setObjectName("label_producer")
        self.label_specialthanks = QtWidgets.QLabel(Window_help)
        self.label_specialthanks.setGeometry(QtCore.QRect(580, 380, 110, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_specialthanks.setFont(font)
        self.label_specialthanks.setObjectName("label_specialthanks")
        self.label_title3 = QtWidgets.QLabel(Window_help)
        self.label_title3.setGeometry(QtCore.QRect(580, 320, 120, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.label_title3.setFont(font)
        self.label_title3.setObjectName("label_title3")

        self.retranslateUi(Window_help)
        QtCore.QMetaObject.connectSlotsByName(Window_help)

    def retranslateUi(self, Window_help):
        _translate = QtCore.QCoreApplication.translate
        Window_help.setWindowTitle(_translate("Window_help", "Form"))
        self.label_title1.setText(_translate("Window_help", "浙江理工大学学生管理系统"))
        self.label_version.setText(_translate("Window_help", "V 1.0.0"))
        self.label_title2.setText(_translate("Window_help", "制作人员"))
        self.label_producer.setText(_translate("Window_help", "张方略，刘恒玮，卢霍东"))
        self.label_specialthanks.setText(_translate("Window_help", "蔡霞老师"))
        self.label_title3.setText(_translate("Window_help", "特别鸣谢"))
