# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'score_delete_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyodbc
from PyQt5.QtCore import QStringListModel

class Ui_Window_score_delete(object):
    def setupUi(self, Window_score_delete):
        Window_score_delete.setObjectName("Window_score_delete")
        Window_score_delete.resize(1280, 721)
        self.label_title1 = QtWidgets.QLabel(Window_score_delete)
        self.label_title1.setGeometry(QtCore.QRect(540, 20, 200, 60))
        self.label_title1.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.label_title1.setFont(font)
        self.label_title1.setObjectName("label_title1")
        self.listView_score = QtWidgets.QListView(Window_score_delete)
        self.listView_score.setGeometry(QtCore.QRect(589, 99, 681, 601))
        self.listView_score.setObjectName("listView_score")
        self.pushButton_delete = QtWidgets.QPushButton(Window_score_delete)
        self.pushButton_delete.setGeometry(QtCore.QRect(460, 220, 100, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.lineEdit_stuno = QtWidgets.QLineEdit(Window_score_delete)
        self.lineEdit_stuno.setGeometry(QtCore.QRect(140, 100, 300, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.lineEdit_stuno.setFont(font)
        self.lineEdit_stuno.setObjectName("lineEdit_stuno")
        self.label_title2 = QtWidgets.QLabel(Window_score_delete)
        self.label_title2.setGeometry(QtCore.QRect(30, 100, 100, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_title2.setFont(font)
        self.label_title2.setObjectName("label_title2")
        self.pushButton_inquiry = QtWidgets.QPushButton(Window_score_delete)
        self.pushButton_inquiry.setGeometry(QtCore.QRect(460, 100, 100, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_inquiry.setFont(font)
        self.pushButton_inquiry.setObjectName("pushButton_inquiry")
        self.label_tip = QtWidgets.QLabel(Window_score_delete)
        self.label_tip.setGeometry(QtCore.QRect(40, 160, 521, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_tip.setFont(font)
        self.label_tip.setText("")
        self.label_tip.setObjectName("label_tip")
        self.lineEdit_courseno = QtWidgets.QLineEdit(Window_score_delete)
        self.lineEdit_courseno.setGeometry(QtCore.QRect(140, 220, 300, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.lineEdit_courseno.setFont(font)
        self.lineEdit_courseno.setObjectName("lineEdit_courseno")
        self.label_title3 = QtWidgets.QLabel(Window_score_delete)
        self.label_title3.setGeometry(QtCore.QRect(30, 220, 100, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_title3.setFont(font)
        self.label_title3.setObjectName("label_title3")
        self.label_tip_2 = QtWidgets.QLabel(Window_score_delete)
        self.label_tip_2.setGeometry(QtCore.QRect(40, 280, 521, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_tip_2.setFont(font)
        self.label_tip_2.setText("")
        self.label_tip_2.setObjectName("label_tip_2")

        self.retranslateUi(Window_score_delete)
        QtCore.QMetaObject.connectSlotsByName(Window_score_delete)
        self.init()
        self.pushButton_inquiry.clicked.connect(lambda: self.inquiry())
        self.pushButton_delete.clicked.connect(lambda: self.delete())

    def retranslateUi(self, Window_score_delete):
        _translate = QtCore.QCoreApplication.translate
        Window_score_delete.setWindowTitle(_translate("Window_score_delete", "Form"))
        self.label_title1.setText(_translate("Window_score_delete", "删除成绩"))
        self.pushButton_delete.setText(_translate("Window_score_delete", "删除"))
        self.label_title2.setText(_translate("Window_score_delete", "学  号："))
        self.pushButton_inquiry.setText(_translate("Window_score_delete", "查询"))
        self.label_title3.setText(_translate("Window_score_delete", "课程号："))

    def init(self):
        self.qList = ["学号\t\t姓名\t班级\t课程号\t课程名\t\t成绩", ]

        conn = pyodbc.connect(r'DRIVER={SQL Server Native Client 11.0};'
                              r'SERVER=Beta;'
                              r'DATABASE=Curriculum_design;'
                              r'UID=Pdocw;'
                              r'PWD=123456'
                              )
        cur = conn.cursor()
        cur.execute("SELECT xsxx.Sno, xsxx.Sname, xsxx.Sclass, xxxx.Cno, Cname, xxxx.Score FROM xsxx, xxxx, kc WHERE xsxx.Sno = xxxx.Sno and xxxx.Cno = kc.Cno")
        row = cur.fetchone()
        while row:
            self.qList.append(str(row[0]) + '\t' + str(row[1]) + '\t' + str(row[2]) + '\t' + str(row[3]) + '\t' + str(row[4]) + '\t' + str(row[5]))
            row = cur.fetchone()
        conn.close()

        slm = QStringListModel(self.qList)
        self.listView_score.setModel(slm)

    def inquiry(self):
        sno = self.lineEdit_stuno.text()
        self.qList = ["学号\t\t姓名\t班级\t课程号\t课程名\t\t成绩", ]
        conn = pyodbc.connect(r'DRIVER={SQL Server Native Client 11.0};'
                              r'SERVER=Beta;'
                              r'DATABASE=Curriculum_design;'
                              r'UID=Pdocw;'
                              r'PWD=123456'
                              )
        cur = conn.cursor()
        if sno != '':
            cur.execute("SELECT xsxx.Sno, xsxx.Sname, xsxx.Sclass, xxxx.Cno, Cname, xxxx.Score FROM xsxx, xxxx, kc WHERE xsxx.Sno = xxxx.Sno and xxxx.Cno = kc.Cno and xsxx.Sno ='" + sno +"'")
        row = cur.fetchone()
        if not row:
            conn.commit()
            conn.close()
        else:
            while row:
                self.qList.append(str(row[0]) + '\t' + str(row[1]) + '\t' + str(row[2]) + '\t' + str(row[3]) + '\t' + str(row[4]) + '\t' + str(row[5]))
                row = cur.fetchone()
            conn.close()
        slm = QStringListModel(self.qList)
        self.listView_score.setModel(slm)

    def delete(self):
        sno = self.lineEdit_stuno.text()
        cno = self.lineEdit_courseno.text()
        print(5)
        conn = pyodbc.connect(r'DRIVER={SQL Server Native Client 11.0};'
                              r'SERVER=Beta;'
                              r'DATABASE=Curriculum_design;'
                              r'UID=Pdocw;'
                              r'PWD=123456'
                              )
        cur = conn.cursor()
        if sno != '':
            cur.execute("SELECT * FROM xxxx WHERE Sno =" + sno + "and Cno ='" + cno + "'")
        print(3)
        row = cur.fetchone()
        if not row:
            conn.commit()
            conn.close()
        else:
            cur.execute("delete from xxxx WHERE Sno =" + sno + "and Cno ='" + cno + "'")
            conn.commit()
            print(row[2])
            cur = conn.cursor()
            cur.execute("update cjpm set TotalScore -= " + str(row[2]) + "WHERE Sno ='" + sno + "'")
            self.label_tip.setText("已成功删除！")
            self.label_tip.setStyleSheet('color:rgb(255, 0, 0)')
            conn.commit()
            conn.close()
