# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stuinfo_inquiry_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual modifys made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pyodbc

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QStringListModel


class Ui_Window_stuinfo_inquiry(object):
    def setupUi(self, Window_stuinfo_inquiry):
        Window_stuinfo_inquiry.setObjectName("Window_stuinfo_inquiry")
        Window_stuinfo_inquiry.resize(1280, 720)
        Window_stuinfo_inquiry.setMinimumSize(QtCore.QSize(1280, 720))
        Window_stuinfo_inquiry.setMaximumSize(QtCore.QSize(1280, 720))
        self.listView_stuinfo = QtWidgets.QListView(Window_stuinfo_inquiry)
        self.listView_stuinfo.setGeometry(QtCore.QRect(600, 20, 660, 641))
        self.listView_stuinfo.setObjectName("listView_stuinfo")
        self.pushButton_clear2 = QtWidgets.QPushButton(Window_stuinfo_inquiry)
        self.pushButton_clear2.setGeometry(QtCore.QRect(470, 260, 90, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_clear2.setFont(font)
        self.pushButton_clear2.setObjectName("pushButton_clear2")
        self.label_title1 = QtWidgets.QLabel(Window_stuinfo_inquiry)
        self.label_title1.setGeometry(QtCore.QRect(40, 20, 300, 60))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.label_title1.setFont(font)
        self.label_title1.setObjectName("label_title1")
        self.label_title3 = QtWidgets.QLabel(Window_stuinfo_inquiry)
        self.label_title3.setGeometry(QtCore.QRect(40, 190, 100, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_title3.setFont(font)
        self.label_title3.setObjectName("label_title3")
        self.label_title2 = QtWidgets.QLabel(Window_stuinfo_inquiry)
        self.label_title2.setGeometry(QtCore.QRect(40, 130, 400, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_title2.setFont(font)
        self.label_title2.setObjectName("label_title2")
        self.lineEdit_stuno = QtWidgets.QLineEdit(Window_stuinfo_inquiry)
        self.lineEdit_stuno.setGeometry(QtCore.QRect(150, 260, 300, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.lineEdit_stuno.setFont(font)
        self.lineEdit_stuno.setObjectName("lineEdit_stuno")
        self.lineEdit_stuname = QtWidgets.QLineEdit(Window_stuinfo_inquiry)
        self.lineEdit_stuname.setGeometry(QtCore.QRect(150, 190, 300, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.lineEdit_stuname.setFont(font)
        self.lineEdit_stuname.setObjectName("lineEdit_stuname")
        self.pushButton_inquiry = QtWidgets.QPushButton(Window_stuinfo_inquiry)
        self.pushButton_inquiry.setGeometry(QtCore.QRect(40, 330, 520, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_inquiry.setFont(font)
        self.pushButton_inquiry.setObjectName("pushButton_inquiry")
        self.label_title4 = QtWidgets.QLabel(Window_stuinfo_inquiry)
        self.label_title4.setGeometry(QtCore.QRect(40, 260, 100, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_title4.setFont(font)
        self.label_title4.setObjectName("label_title4")
        self.pushButton_clear1 = QtWidgets.QPushButton(Window_stuinfo_inquiry)
        self.pushButton_clear1.setGeometry(QtCore.QRect(470, 190, 90, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_clear1.setFont(font)
        self.pushButton_clear1.setObjectName("pushButton_clear1")

        self.retranslateUi(Window_stuinfo_inquiry)
        QtCore.QMetaObject.connectSlotsByName(Window_stuinfo_inquiry)

        # 初始化
        self.init()
        # 清空
        self.pushButton_clear1.clicked.connect(lambda: self.clear())
        self.pushButton_clear2.clicked.connect(lambda: self.clear())
        # 查询
        self.pushButton_inquiry.clicked.connect(lambda: self.inquiry())

    def retranslateUi(self, Window_stuinfo_inquiry):
        _translate = QtCore.QCoreApplication.translate
        Window_stuinfo_inquiry.setWindowTitle(_translate("Window_stuinfo_inquiry", "Form"))
        self.pushButton_clear2.setText(_translate("Window_stuinfo_inquiry", "清空"))
        self.label_title1.setText(_translate("Window_stuinfo_inquiry", "学生信息查询"))
        self.label_title3.setText(_translate("Window_stuinfo_inquiry", "姓  名："))
        self.label_title2.setText(_translate("Window_stuinfo_inquiry", "请输入查询条件（二选一）"))
        self.pushButton_inquiry.setText(_translate("Window_stuinfo_inquiry", "查询"))
        self.label_title4.setText(_translate("Window_stuinfo_inquiry", "学  号："))
        self.pushButton_clear1.setText(_translate("Window_stuinfo_inquiry", "清空"))

    def init(self):
        self.qList = ["学号\t\t姓名\t\t性别\t班级\t年龄", ]

        conn = pyodbc.connect(r'DRIVER={SQL Server Native Client 11.0};'
                              r'SERVER=Beta;'
                              r'DATABASE=Curriculum_design;'
                              r'UID=Pdocw;'
                              r'PWD=123456'
                              )
        cur = conn.cursor()
        cur.execute('SELECT * FROM xsxx')
        row = cur.fetchone()
        while row:
            self.qList.append(str(row[0]).strip() + '\t' + str(row[1]).strip() + '\t\t' + str(row[2]) + '\t' + str(row[3]).strip() + '\t' + str(row[4]))
            row = cur.fetchone()
        conn.close()

        slm = QStringListModel(self.qList)
        self.listView_stuinfo.setModel(slm)

    def clear(self):
        self.lineEdit_stuno.setText("")
        self.lineEdit_stuname.setText("")
        self.init()

    def inquiry(self):
        sno = self.lineEdit_stuno.text()
        sname = self.lineEdit_stuname.text()
        self.qList = ["学号\t\t姓名\t\t性别\t班级\t年龄", ]

        conn = pyodbc.connect(r'DRIVER={SQL Server Native Client 11.0};'
                              r'SERVER=Beta;'
                              r'DATABASE=Curriculum_design;'
                              r'UID=Pdocw;'
                              r'PWD=123456')
        cur = conn.cursor()

        if sno != '':
            cur.execute("SELECT * FROM xsxx WHERE Sno = '" + sno + "'")
        elif sname != '':
            cur.execute("SELECT * FROM xsxx WHERE Sname = '" + sname + "'")
        else:
            return

        row = cur.fetchone()
        if not row:
            # QtWidgets.QMessageBox.warning(QtWidgets.QWidget(), "错误", "课程号和课程名不匹配或不存在", QtWidgets.QMessageBox.Yes,
            #                               QtWidgets.QMessageBox.Yes)
            self.qList.append('NULL\t\tNULL\t\tNULL\tNULL\tNULL')
        else:
            while row:
                self.qList.append(str(row[0]).strip() + '\t' + str(row[1]).strip() + '\t\t' + str(row[2]) + '\t' + str(row[3]).strip() + '\t' + str(row[4]))
                row = cur.fetchone()
            conn.close()

        slm = QStringListModel(self.qList)
        self.listView_stuinfo.setModel(slm)
