# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stuinfo_modify_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyodbc

class Ui_Window_stuinfo_modify(object):
    def setupUi(self, Window_stuinfo_modify):
        Window_stuinfo_modify.setObjectName("Window_stuinfo_modify")
        Window_stuinfo_modify.resize(1280, 720)
        Window_stuinfo_modify.setMinimumSize(QtCore.QSize(1280, 720))
        Window_stuinfo_modify.setMaximumSize(QtCore.QSize(1280, 720))
        self.lineEdit_stuage = QtWidgets.QLineEdit(Window_stuinfo_modify)
        self.lineEdit_stuage.setGeometry(QtCore.QRect(290, 310, 300, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.lineEdit_stuage.setFont(font)
        self.lineEdit_stuage.setObjectName("lineEdit_stuage")
        self.label_title3 = QtWidgets.QLabel(Window_stuinfo_modify)
        self.label_title3.setGeometry(QtCore.QRect(200, 310, 100, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_title3.setFont(font)
        self.label_title3.setObjectName("label_title3")
        self.lineEdit_stuname = QtWidgets.QLineEdit(Window_stuinfo_modify)
        self.lineEdit_stuname.setGeometry(QtCore.QRect(720, 310, 300, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.lineEdit_stuname.setFont(font)
        self.lineEdit_stuname.setObjectName("lineEdit_stuname")
        self.lineEdit_stuno = QtWidgets.QLineEdit(Window_stuinfo_modify)
        self.lineEdit_stuno.setGeometry(QtCore.QRect(480, 130, 300, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.lineEdit_stuno.setFont(font)
        self.lineEdit_stuno.setObjectName("lineEdit_stuno")
        self.lineEdit_stuno.setValidator(QtGui.QIntValidator())
        self.pushButton_modify = QtWidgets.QPushButton(Window_stuinfo_modify)
        self.pushButton_modify.setGeometry(QtCore.QRect(430, 520, 180, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_modify.setFont(font)
        self.pushButton_modify.setObjectName("pushButton_modify")
        self.label_title1 = QtWidgets.QLabel(Window_stuinfo_modify)
        self.label_title1.setGeometry(QtCore.QRect(490, 20, 300, 60))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.label_title1.setFont(font)
        self.label_title1.setObjectName("label_title1")
        self.label_title2 = QtWidgets.QLabel(Window_stuinfo_modify)
        self.label_title2.setGeometry(QtCore.QRect(350, 130, 100, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_title2.setFont(font)
        self.label_title2.setObjectName("label_title2")
        self.label_title5 = QtWidgets.QLabel(Window_stuinfo_modify)
        self.label_title5.setGeometry(QtCore.QRect(200, 400, 100, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_title5.setFont(font)
        self.label_title5.setObjectName("label_title5")
        self.lineEdit_stusex = QtWidgets.QLineEdit(Window_stuinfo_modify)
        self.lineEdit_stusex.setGeometry(QtCore.QRect(720, 400, 300, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.lineEdit_stusex.setFont(font)
        self.lineEdit_stusex.setObjectName("lineEdit_stusex")
        self.label_title4 = QtWidgets.QLabel(Window_stuinfo_modify)
        self.label_title4.setGeometry(QtCore.QRect(630, 310, 100, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_title4.setFont(font)
        self.label_title4.setObjectName("label_title4")
        self.lineEdit_stuclass = QtWidgets.QLineEdit(Window_stuinfo_modify)
        self.lineEdit_stuclass.setGeometry(QtCore.QRect(290, 400, 300, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.lineEdit_stuclass.setFont(font)
        self.lineEdit_stuclass.setObjectName("lineEdit_stuclass")
        self.label_title6 = QtWidgets.QLabel(Window_stuinfo_modify)
        self.label_title6.setGeometry(QtCore.QRect(630, 400, 100, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_title6.setFont(font)
        self.label_title6.setObjectName("label_title6")
        self.pushButton_inquiry = QtWidgets.QPushButton(Window_stuinfo_modify)
        self.pushButton_inquiry.setGeometry(QtCore.QRect(810, 130, 100, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_inquiry.setFont(font)
        self.pushButton_inquiry.setObjectName("pushButton_inquiry")
        self.pushButton_cancel = QtWidgets.QPushButton(Window_stuinfo_modify)
        self.pushButton_cancel.setGeometry(QtCore.QRect(650, 520, 180, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.label_tip = QtWidgets.QLabel(Window_stuinfo_modify)
        self.label_tip.setGeometry(QtCore.QRect(370, 210, 521, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_tip.setFont(font)
        self.label_tip.setText("")
        self.label_tip.setObjectName("label_tip")

        self.retranslateUi(Window_stuinfo_modify)
        QtCore.QMetaObject.connectSlotsByName(Window_stuinfo_modify)

        self.pushButton_inquiry.clicked.connect(lambda: self.inquiry())
        self.pushButton_cancel.clicked.connect(lambda: self.inquiry())
        self.pushButton_modify.clicked.connect(lambda: self.modify())
    def retranslateUi(self, Window_stuinfo_modify):
        _translate = QtCore.QCoreApplication.translate
        Window_stuinfo_modify.setWindowTitle(_translate("Window_stuinfo_modify", "Form"))
        self.label_title3.setText(_translate("Window_stuinfo_modify", "年龄："))
        self.pushButton_modify.setText(_translate("Window_stuinfo_modify", "修改"))
        self.label_title1.setText(_translate("Window_stuinfo_modify", "修改学生信息"))
        self.label_title2.setText(_translate("Window_stuinfo_modify", "学  号："))
        self.label_title5.setText(_translate("Window_stuinfo_modify", "班级："))
        self.label_title4.setText(_translate("Window_stuinfo_modify", "姓名："))
        self.label_title6.setText(_translate("Window_stuinfo_modify", "性别："))
        self.pushButton_inquiry.setText(_translate("Window_stuinfo_modify", "查询"))
        self.pushButton_cancel.setText(_translate("Window_stuinfo_modify", "取消"))

    def inquiry(self):
        sno = self.lineEdit_stuno.text()
        conn = pyodbc.connect(r'DRIVER={SQL Server Native Client 11.0};'
                              r'SERVER=Beta;'
                              r'DATABASE=Curriculum_design;'
                              r'UID=Pdocw;'
                              r'PWD=123456'
                              )
        cur = conn.cursor()
        if sno != '':
            cur.execute('SELECT * FROM xsxx WHERE Sno =' + sno)
        else:
            return
        row = cur.fetchone()
        if not row:
            QtWidgets.QMessageBox.warning(QtWidgets.QWidget(), "错误", "学号不存在", QtWidgets.QMessageBox.Yes,
                                          QtWidgets.QMessageBox.Yes)
            conn.close()
        else:
            sname = row[1].strip()
            sex = row[2].strip()
            sclass = row[3].strip()
            sage = str(row[4]).strip()
            self.lineEdit_stuname.setText(sname)
            self.lineEdit_stusex.setText(sex)
            self.lineEdit_stuclass.setText(sclass)
            self.lineEdit_stuage.setText(sage)
            conn.commit()
            conn.close()

    def modify(self):
        sno = self.lineEdit_stuno.text()
        conn = pyodbc.connect(r'DRIVER={SQL Server Native Client 11.0};'
                              r'SERVER=Beta;'
                              r'DATABASE=Curriculum_design;'
                              r'UID=Pdocw;'
                              r'PWD=123456'
                              )
        cur = conn.cursor()
        if sno != '':
            cur.execute('SELECT * FROM xsxx WHERE Sno =' + sno)
        row = cur.fetchone()
        if not row:
            conn.commit()
            conn.close()
        else:
            sname = self.lineEdit_stuname.text()
            sage = self.lineEdit_stuage.text()
            sclass = self.lineEdit_stuclass.text()
            sex = self.lineEdit_stusex.text()
            cur.execute("delete from xsxx WHERE Sno =" + sno)
            conn.commit()
            cur.execute("insert into xsxx values('" + sno + "','" + sname + "','" + sex + "','" + sclass + "','" + sage + "')")
            QtWidgets.QMessageBox.warning(QtWidgets.QWidget(), "提示", "已经成功修改！", QtWidgets.QMessageBox.Yes,
                                          QtWidgets.QMessageBox.Yes)
            conn.commit()
            conn.close()

